### PR TITLE
Dynamic Debug-Views onclick

### PR DESCRIPTION
**Pull request by puschie286**
here is the comment replacement function

only the toggleViewHints function has changed - dont know why the whole file is marked as changed

### CODE REVIEW

**Comment by natanfelles** [comment]
Uhull. 😄 

Very nice. But...

I noticed a problem. See the image below, the views hints are getting one inside the other. But they should stay one after the other. Maybe it's time to close the div.

screenshot from 2017-10-16 13-31-26

screenshot from 2017-10-16 13-31-52

**Comment by puschie286** [comment]
hmm, i see^^ looks like a problem with the start/end position calculation. im on it

i also found another problem^^ - if we have the same view multiple time, it create just one container for it ( currently i differentiate the view by the path ). maybe we need to count them and add the number to the comment

**Comment by puschie286** [comment]
im not sure were to add the view file counting - would be great if you could add it ( there are no change necessary in the js code )

**Comment by natanfelles** [comment]
What the format you think?

Something simple like:

```
<!-- DEBUG-VIEW START 1 - APPPATH/Views/welcome.php -->
```

My thought is about where to save this counter.

**Comment by puschie286** [comment]
Yea - it depends where the counter should be shown in the view.

**Comment by natanfelles** [comment]
@puschie286 Please, reply on the [PR](https://github.com/bcit-ci/CodeIgniter4/pull/767#issuecomment-337338944).

**Pull request merged**
